s = 'Hello this is string'
print('s:', s)
print('s.upper() gives:', s.upper())
print('s.lower gives:', s.lower())
print('s.capitalize gives:', s.capitalize())
print('s.title gives:', s.title())
print('s.casefold gives:', s.casefold())
print('s.swapcase gives:', s.swapcase())
print('s.split gives:', s.split())
print('s.splitlines gives:', s.splitlines())
